# @package _global_

dim: 2

energy:
  _target_: adjoint_samplers.energies.dist_energy.DistEnergy
  dist:
    _target_: adjoint_samplers.utils.dist_utils.GMM2D

evaluator:
  _target_: adjoint_samplers.components.evaluator.GMM2DEvaluator
  num_reference_samples: ${num_eval_samples}